import { createHash, randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { chmod, copyFile, mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { audiogramFileForState, audiogramRequestForDraft, queueAudiogram, readAudiogramState, reconcileAudiograms } from "./audiogram-jobs.mjs";
import { completeDatabaseAudiogram, failDatabaseAudiogram, listActiveDatabaseAudiograms, queueDatabaseAudiogram, readDatabaseAudiogramState, startDatabaseAudiogram } from "./database-audiograms.mjs";

const TIMEOUT_MS=35*60*1000;
async function optionalJson(path){try{return JSON.parse(await readFile(path,"utf8"));}catch(error){if(error.code==="ENOENT")return null;throw error;}}
async function digest(path){return createHash("sha256").update(await readFile(path)).digest("hex");}
export function filesystemAudiogramStore({queueRoot,statesRoot,jobsRoot}){return{queue:(value)=>queueAudiogram({...value,queueRoot,statesRoot}),read:(id)=>readAudiogramState(statesRoot,id),file:(state)=>audiogramFileForState(state,jobsRoot),reconcile:(callbacks)=>reconcileAudiograms({statesRoot,jobsRoot,...callbacks})};}
export function databaseAudiogramStore({database,queueRoot,jobsRoot,artifactsRoot}){return{
 async queue({draft,audio,now=new Date()}){const request=audiogramRequestForDraft(draft,audio);const jobId=`audiogram-es-${draft.articleId.replaceAll("-","")}-r${draft.revision}-${randomUUID().slice(0,8)}`;const state=queueDatabaseAudiogram(database,{draft,request,jobId,now});if(state.jobId!==jobId)return state;const temporary=join(queueRoot,`.${jobId}.${randomUUID()}.queuing`);try{await mkdir(queueRoot,{recursive:true,mode:0o700});await mkdir(temporary,{mode:0o700});await writeFile(join(temporary,"request.json"),`${JSON.stringify(request,null,2)}\n`,{mode:0o600,flag:"wx"});await rename(temporary,join(queueRoot,jobId));await writeFile(join(queueRoot,".wake"),"\n",{mode:0o600});}catch(error){failDatabaseAudiogram(database,jobId,"audiogram request could not be queued",now);throw error;}return state;},
 async read(id){return readDatabaseAudiogramState(database,id);},file(state){if(state.status!=="completed"||!state.artifact?.path)throw new Error("audiogram is not ready");return state.artifact.path;},
 async reconcile({onComplete,onFailure,now=new Date()}){for(const active of listActiveDatabaseAudiograms(database)){const root=join(jobsRoot,active.jobId);const result=await optionalJson(join(root,"video","result.json"));if(result){const source=join(root,"video",basename(result.file));const metadata=await stat(source);if(!metadata.isFile()||metadata.size!==result.sizeBytes||await digest(source)!==result.sha256)throw new Error("audiogram result checksum is invalid");const directory=join(artifactsRoot,active.articleId);const path=join(directory,`${result.sha256}.mp4`);await mkdir(directory,{recursive:true,mode:0o700});try{const existing=await stat(path);if(!existing.isFile()||await digest(path)!==result.sha256)throw new Error("audiogram artifact differs");}catch(error){if(error.code!=="ENOENT")throw error;await copyFile(source,path,constants.COPYFILE_EXCL);await chmod(path,0o600);}if(active.status==="queued")startDatabaseAudiogram(database,active.jobId,now);const completed=completeDatabaseAudiogram(database,{jobId:active.jobId,result,artifactPath:path,now});await onComplete?.(completed);continue;}if(active.status==="queued"&&await optionalJson(join(root,"request.json")))startDatabaseAudiogram(database,active.jobId,now);if(now.getTime()-Date.parse(active.createdAt)>TIMEOUT_MS){const failed=failDatabaseAudiogram(database,active.jobId,"El audiograma excedió su límite automático.",now);await onFailure?.(failed);}}}
};}
