import { createHash, randomUUID } from "node:crypto";
import { withTransaction } from "./database.mjs";

const digest=(value)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const MUSIC_JOB = /^release-[0-9a-f]{32}-r1-[0-9a-f]{8}$/;
const SELECT=`SELECT j.id AS job_id,j.status AS job_status,j.checkpoint_json,j.created_at,j.started_at,j.heartbeat_at,j.finished_at,j.error_message,
  rel.status AS release_status,rel.manifest_json,d.status AS deployment_status,d.verification_json,d.immutable_url
  FROM jobs j JOIN releases rel ON rel.id=j.id LEFT JOIN deployments d ON d.release_id=rel.id WHERE j.type='music_release'`;
function state(row){if(!row)return null;const saved=JSON.parse(row.checkpoint_json||"{}");const statuses={queued:"queued",leased:"running",retry_wait:"queued",completed:"completed",failed:"failed",cancelled:"failed"};return{schemaVersion:1,jobId:row.job_id,status:statuses[row.job_status],createdAt:row.created_at,updatedAt:row.finished_at??row.heartbeat_at??row.started_at??row.created_at,...(row.immutable_url?{deploymentUrl:row.immutable_url}:{}),...(row.error_message?{error:row.error_message}:{}),...(saved.settings?{settings:saved.settings}:{})};}
export function readDatabaseMusicSettings(database){const row=database.prepare("SELECT settings_json FROM site_settings_revisions ORDER BY created_at DESC,id DESC LIMIT 1").get();if(!row){const error=new Error("music settings were not found");error.code="ENOENT";throw error;}return JSON.parse(row.settings_json);}
export function saveDatabaseMusicSettings(database,settings,now=new Date()){const id=`settings:${digest(settings)}:${randomUUID()}`;database.prepare("INSERT INTO site_settings_revisions(id,settings_json,created_at) VALUES(?,?,?)").run(id,JSON.stringify(settings),now.toISOString());return settings;}
export function readDatabaseMusicPublication(database){const row=database.prepare(`${SELECT} ORDER BY j.created_at DESC,j.id DESC LIMIT 1`).get();return state(row);}
export function queueDatabaseMusicPublication(database,{settings,jobId,path,now=new Date()}){if(!MUSIC_JOB.test(jobId??"")||typeof path!=="string")throw new Error("music release request is invalid");return withTransaction(database,(connection)=>{const dependency=digest(settings);const existing=connection.prepare(`${SELECT} AND j.idempotency_key=?`).get(`music:${dependency}`);if(existing)return state(existing);if(connection.prepare("SELECT 1 FROM jobs WHERE type IN ('music_release','deployment') AND status IN ('queued','leased','retry_wait')").get())throw new Error("Ya hay una publicación en curso.");const source=connection.prepare("SELECT rel.id,rel.catalog_id FROM deployments d JOIN releases rel ON rel.id=d.release_id WHERE d.status='published' ORDER BY d.published_at DESC,d.id DESC LIMIT 1").get();if(!source)throw new Error("a validated selected release is required");const timestamp=now.toISOString();const json=JSON.stringify(settings);let settingsRow=connection.prepare("SELECT id FROM site_settings_revisions WHERE settings_json=? ORDER BY created_at DESC,id DESC LIMIT 1").get(json);if(!settingsRow){settingsRow={id:`settings:${dependency}:${randomUUID()}`};connection.prepare("INSERT INTO site_settings_revisions(id,settings_json,created_at) VALUES(?,?,?)").run(settingsRow.id,json,timestamp);}connection.prepare("INSERT INTO releases(id,catalog_id,site_settings_revision_id,status,path,created_at) VALUES(?,?,?,'building',?,?)").run(jobId,source.catalog_id,settingsRow.id,path,timestamp);connection.prepare("INSERT INTO release_artifacts(release_id,artifact_id,checksum_sha256) SELECT ?,artifact_id,checksum_sha256 FROM release_artifacts WHERE release_id=?").run(jobId,source.id);connection.prepare(`INSERT INTO jobs(id,type,revision_id,artifact_id,idempotency_key,dependency_hash,status,checkpoint_json,available_at,created_at) VALUES(?,'music_release',NULL,NULL,?,?,'queued',?,?,?)`).run(jobId,`music:${dependency}`,dependency,JSON.stringify({schemaVersion:1,settings}),timestamp,timestamp);return state(connection.prepare(`${SELECT} AND j.id=?`).get(jobId));});}
export function startDatabaseMusicPublication(database,jobId,now=new Date()){const changed=database.prepare("UPDATE jobs SET status='leased',attempt=attempt+1,lease_owner='systemd',lease_expires_at=?,heartbeat_at=?,started_at=COALESCE(started_at,?) WHERE id=? AND type='music_release' AND status='queued'").run(new Date(now.getTime()+30*60*1000).toISOString(),now.toISOString(),now.toISOString(),jobId);if(changed.changes!==1)throw new Error("music publication is not queued");}
export function completeDatabaseMusicPublication(database,{jobId,manifest,manifestChecksum,receipt,now=new Date()}){if(manifest?.schemaVersion!==1||manifest.releaseKind!=="music"||!Number.isFinite(Date.parse(manifest.buildCompletedAt??""))||!/^[0-9a-f]{64}$/.test(manifestChecksum??"")||receipt?.schemaVersion!==1||receipt.environment!=="production"||receipt.jobId!==jobId||!/^https:\/\/[a-zA-Z0-9.-]+\.pages\.dev$/.test(receipt.url??"")||!Number.isFinite(Date.parse(receipt.validatedAt??"")))throw new Error("music publication evidence is invalid");return withTransaction(database,(connection)=>{const timestamp=now.toISOString();const release=connection.prepare("UPDATE releases SET status='validated',manifest_json=?,manifest_checksum_sha256=?,validated_at=? WHERE id=? AND status='building'").run(JSON.stringify(manifest),manifestChecksum,manifest.buildCompletedAt,jobId);const previous=connection.prepare("SELECT id FROM deployments WHERE status='published' ORDER BY published_at DESC,id DESC LIMIT 1").get();const deploymentId=`music-deploy:${jobId}`;connection.prepare(`INSERT INTO deployments(id,release_id,status,cloudflare_deployment_id,immutable_url,verification_json,previous_deployment_id,created_at,published_at,finished_at) VALUES(?,?,'published',?,?,?,?,?,?,?)`).run(deploymentId,jobId,new URL(receipt.url).hostname.split(".")[0],receipt.url,JSON.stringify(receipt),previous?.id??null,timestamp,receipt.validatedAt,timestamp);const saved=JSON.parse(connection.prepare("SELECT checkpoint_json FROM jobs WHERE id=?").get(jobId).checkpoint_json);const job=connection.prepare("UPDATE jobs SET status='completed',checkpoint_json=?,heartbeat_at=?,finished_at=?,lease_owner=NULL,lease_expires_at=NULL WHERE id=? AND status='leased'").run(JSON.stringify({...saved,manifest,receipt}),timestamp,timestamp,jobId);if(release.changes!==1||job.changes!==1)throw new Error("music publication is not running");return state(connection.prepare(`${SELECT} AND j.id=?`).get(jobId));});}
export function failDatabaseMusicPublication(database,jobId,message,now=new Date()){return withTransaction(database,(connection)=>{const timestamp=now.toISOString();const job=connection.prepare("UPDATE jobs SET status='failed',error_message=?,heartbeat_at=?,finished_at=?,lease_owner=NULL,lease_expires_at=NULL WHERE id=? AND type='music_release' AND status IN ('queued','leased','retry_wait')").run(message,timestamp,timestamp,jobId);if(job.changes!==1)throw new Error("music publication cannot be failed");connection.prepare("UPDATE releases SET status='failed',error_message=? WHERE id=? AND status='building'").run(message,jobId);return state(connection.prepare(`${SELECT} AND j.id=?`).get(jobId));});}
export function musicJobId(){const article=randomUUID();return`release-${article.replaceAll("-","")}-r1-${randomUUID().slice(0,8)}`;}
